[phases.setup]
nixPkgs = ['nodejs', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile --prod=false']

[phases.build]
cmds = ['pnpm run build']

[phases.setup-production]
cmds = ['pnpm prune --prod']

[start]
cmd = 'pnpm run update-cache && pnpm start'

[variables]
NODE_ENV = 'production'
NEXT_TELEMETRY_DISABLED = '1'
PORT = '3000'
HOST = '0.0.0.0'